[package]
name = "autd3-emulator"
description = "autd3 emulator for calculating sound field, emulation of firmware, etc"
readme = "README.md"
keywords = ["autd"]
version = "29.0.0-rc.13"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/shinolab/autd3-emulator"

[dependencies]
autd3 = { version = "29.0.0-rc.13" }
autd3-firmware-emulator = { version = "29.0.0-rc.13" }
derive_more = { version = "1.0.0", default-features = false }
polars = { version = "0.45.1", features = ["dtype-u16", "dtype-u8"], default-features = false }
indicatif = { version = "0.17.9", default-features = false }
itertools = { version = "0.14.0", default-features = false }
thiserror = { version = "2.0.9", default-features = false }
unzip3 = "1.0.0"
bvh = { version = "0.10.0", default-features = false }
rayon = "1.10.0"
bytemuck = { version = "1.21.0", optional = true }
wgpu = { version = "23.0.1", optional = true }
flume = { version = "0.11.1", optional = true, features = ["async"], default-features = false }
visibility = "0.1.1"
paste = "1.0.15"

[dev-dependencies]
anyhow = { version = "1.0.95", default-features = false }
approx = { version = "0.5.1", default-features = false }
rstest = { version = "0.24.0", default-features = false }
textplots = "0.8.6"
tokio = { version = "1.42.0", features = ["macros"] }
polars = { version = "0.45.1", features = ["csv", "fmt"], default-features = false }
rand = { version = "0.8.5", default-features = false }

[features]
default = []
async-trait = ["autd3/async-trait"]
gpu = ["wgpu", "bytemuck", "flume"]
inplace = []

[package.metadata.docs.rs]
features = ["async-trait", "gpu"]
rustdoc-args = ["--cfg", "docsrs"]
