[package]
name = "autd3-emulator"
description = "autd3 emulator for calculating sound field, emulation of firmware, etc"
readme = "README.md"
keywords = ["autd"]
version = "29.0.0-rc.7.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/shinolab/autd3-emulator"

[dependencies]
autd3 = { version = "29.0.0-rc.7" }
autd3-firmware-emulator = { version = "29.0.0-rc.7" }
derive_more = { version = "1.0.0", features = ["deref"] }
polars = { version = "0.44.0", features = ["dtype-u8"], default-features = false }
indicatif = "0.17.8"
itertools = "0.13.0"
thiserror = "2.0.0"
unzip3 = "1.0.0"
bvh = { version = "0.10.0", default-features = false }
rayon = "1.10.0"
bytemuck = { version = "1.18.0", features = ["derive"], optional = true }
wgpu = { version = "23.0.0", optional = true }
flume = { version = "0.11.0", optional = true }
visibility = "0.1.1"

[dev-dependencies]
anyhow = "1.0.87"
approx = "0.5.1"
rstest = "0.23.0"
textplots = "0.8.6"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
polars = { version = "0.44.0", features = ["dtype-u8", "csv"] }
nalgebra = "0.33.0"
rand = "0.8.5"

[features]
default = []
async-trait = ["autd3/async-trait"]
gpu = ["wgpu", "bytemuck", "flume"]
inplace = []
