name: 'build tools setup action'
inputs:
  components:
    description: 'components'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: ${{ inputs.components }}

    - name: setup cache
      uses: swatinem/rust-cache@v2
