name: build

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-on-${{ matrix.os }}${{ matrix.features && '-' }}${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            features: ""
          - os: ubuntu-latest
            features: ""
          - os: macos-latest
            features: "gpu"
          - os: ubuntu-latest
            features: "async-trait"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - run: |
          cargo nextest run --features "${{ matrix.features }}"
          cargo clippy --features "${{ matrix.features }}" -- -D warnings
        shell: bash
